### ISSUE TITLE
Input Field Bg Color Updates

### ISSUE THREAD

**Issue by emclaug2** [pxblue/themes#102]
#### Describe the bug
Input field `filled` variant does not match angular.  Should React be updated to match, or should angular? 

#### What is the expected behavior?
They both match.

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/6538289/91986419-b3c17280-ecfa-11ea-9c9b-fe631fbf704d.png)
=

**Comment by joebochill** [comment]
These different colors are the defaults from React/Angular respectively. We will need to add theme rules to change them.
In the DSM we are using white[200]...we will probably want to update both to use this value.
