### ISSUE TITLE
Add Ng-Drawer Border/Shadow Color

### ISSUE THREAD

**Issue by emclaug2** [pxblue/themes#117]
#### Describe the desired behavior
pxb-blue and pxb-blueDark theme should add border/shadow colors for the PXB Drawer.

#### Describe the current behavior
Angular Drawer component has a border & shadow option with default colors.

#### Is this request related to a current issue?
No

**Comment by joebochill** [comment]
We are still working on settling on what color we will use for these shadows.

**Comment by joebochill** [comment]
We're currently using a black 500 shadow with 4px blur

**Comment by huayunh** [comment]
I think we are trying to push for 6dp. `0 0 4px 0 #424e54;` is def wrong.

I should prob spend some time consolidating all the shadows & elevations, which unfortunately would not happen in 2020...

**Comment by huayunh** [comment]
This topic might fit well with the "page layout" pattern we've been talking about.

**Comment by emclaug2** [comment]
This might not be required anymore because the drawer shadow was replaced with a mat elevation class.

**Comment by joebochill** [comment]
@emclaug2 is this still an issue?

**Comment by emclaug2** [comment]
I'm not sure if this is still an issue; I'll look into it and close it if this is already fixed.

**Comment by huayunh** [comment]
Fixed; mat-elevation-z6 class applied
