### ISSUE TITLE
Change error state text field border stroke depends on if certain thing is active or inactive

### ISSUE THREAD

**Issue by huayunh** [pxblue/themes#122]
# Describe the desired behavior

Text field border stroke should change to 1px when the text field is "inactive with error", and 2px when the text field is "active with error", like this from DSM:

![image](https://user-images.githubusercontent.com/8997218/102367257-8cc83d00-3f87-11eb-8ea6-fdba349ad336.png)

# Describe the current behavior

Everything in the error state is 2px. 

# Is this request related to a current issue?

NO

# Additional Context
- On their website, Material Design shows a mix of both. Consulted Studio Blue and we agreed that the 2px & 1px is the optimal design.
- Angular Material does what's described above by default, so there is no need to change that on the ng side.
- This active v. inactive thing is correct when the text field is not on the error state.

**Comment by emclaug2** [comment]
Does this also apply to react native?

**Comment by huayunh** [comment]
I didn't check that far...

**Comment by huayunh** [comment]
(I don't think React Native Paper theme allows you to customize things that far)
