### ISSUE TITLE
Dark Theme Input Hint Text Inconsistencies

### ISSUE THREAD

**Issue by emclaug2** [pxblue/themes#125]
#### Describe the bug
Hint Text on input field is slightly different between input variants. 

#### What is the expected behavior?
They should be consistent. 

#### What are the steps to reproduce?
Run the showcase, enable dark mode, look at the input field. 

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/6538289/103678610-b99dbd80-4f51-11eb-9d42-59ef88c4bef6.png)

#### Environment

Chrome/Windows

**Comment by emclaug2** [comment]
The circled hint-text is lighter than the hint-text below it.

**Comment by huayunh** [comment]
![image](https://user-images.githubusercontent.com/8997218/103678738-e9e55c00-4f51-11eb-917e-6f691ae90909.png)
black 200 for assistive text

red 200 for error text

**Comment by emclaug2** [comment]
Looks fixed to me!
