### ISSUE TITLE
Angular Light Theme Enhancements

### ISSUE THREAD

**Issue by emclaug2** [pxblue/themes#137]
## General
For the showcase itself
* [ ]  Showcase background color white[200]
* [ ]  Set the app bar to primary variant
* [ ]  Give that app bar a 4dp shadow

## Tabs
* [ ] Font weight should be 600 for active item, 400 inactive
* [ ] Active tab should retain on-select after non-focus
* [ ]  the light theme tabs are using dark chevrons and the active tab item's bottom borders are blue / invisible

## Snack bar
* [ ] Background black[900], text black[50], action button blue[200]

## Mobile Stepper
* [ ]  "currently inactive dot" gray[200]
 
## Date picker
* [ ]  The circled date for "current year" & "today", should have a blue[500] circle
* [ ]  the calendar icon should be 24x24

## Button Toggle
* [ ] make the default a primary variant (?) 

## Buttons
Comments on the light theme:
    
* [ ]  I actually kinda like how the raised basic button and the stroked basic button look in your implementation, but I dislike the way it is done in flat buttons. May want to involve @joebochill  here to steer away from gray default buttons. This is also available in Figma.
![image](https://user-images.githubusercontent.com/8997218/109067619-bf479200-76bc-11eb-8f93-69619fd969d0.png)
* [ ]  For a raised button, when the mouse is hovering on the button, the button should change its elevation to 4dp
* [ ]  stroked warning button, its outline should be red500
* [ ]  stroked disabled button, its outline should not be darker than that of an enabled button
 

## Chips
* [ ]  Look like this:
![image](https://user-images.githubusercontent.com/6538289/109354665-2e9fbc00-784c-11eb-9921-fdd16ae28343.png)

## Progress Bar
* [ ]  I just added a suggested style for the dark theme progress bar... I forgot about this one. cc @joebochill

 * [ ]  still incorrect.

## Slider
* [ ]  Tick marks blue[200], fill color blue[300], empty color black[100] 

## Checkbox
* [ ]  Set correct disabled theme :  black500 30%

 ## Input fields
Aside from what's mentioned in the time picker section and #123,
 
 ### primary
* [ ]  the hint text is still using different colors
* [ ]  outlined form field, the user input text should be centered in the text field
* [ ]  The inactive filled text field is wrong
* [ ]  If possible, on hover should not make the border 2px. See design file.
 
### warn
* [ ]  red500 borders.

### Disabled
Dark theme
* [ ]  hint color appears different between the legacy field and other ones. They should all be using disabled color.
* [ ]  Icon color should be the disabled color too.
* [ ]  Filled variant: background color should be black800 50%.

## Stepper
* [ ]  Font size changes when an item is selected
* [ ] Fixed colors

**Comment by huayunh** [comment]
> make the default a primary variant

I prob meant to say that the default toggle button should look like that of a primary colored button, like it should look blue-ish...

**Comment by jeffvg** [comment]
moved to PXBLUE-1901
