### ISSUE TITLE
React theme enhancement

### ISSUE THREAD

**Issue by huayunh** [pxblue/themes#138]
# Button 
- [ ] Button - dark theme - enabled state - hover, the background color should be the hover color (black50 10%)

# Stepper
- [ ] Currently active step, text in the blue circle should be weight 600. Other steps, visited or unvisited, should be the regular caption font
- [ ] dark theme, visited steps, label text, textSecondary. No changes for the light theme

# Tabs
- [ ] when you add an `icon={<MailIcon />}` to the `<Tab />` and make it an up-down structure, the icon should not have that bottom margin that pushes the label text and icon away from each other

# Text Fields
- [ ] Light theme, helper text in a disabled text field should also have a disabled color.

**Comment by joebochill** [comment]
> # Button
> * [ ]  Button - dark theme - enabled state - hover, the background color should be the hover color (black50 10%)

Current implementation matches what is specified in Figma Dark Theme Study:
![image](https://user-images.githubusercontent.com/29152776/109507206-7a30b080-7a6c-11eb-8a07-b632376cb6bf.png)
![image](https://user-images.githubusercontent.com/29152776/109507334-9fbdba00-7a6c-11eb-9edd-2da2b335689b.png)

**Comment by huayunh** [comment]
![image](https://user-images.githubusercontent.com/8997218/109521424-4c069d00-7a7b-11eb-9308-14a26e9bfbe4.png)

![image](https://user-images.githubusercontent.com/8997218/109521475-588af580-7a7b-11eb-8997-05df46990867.png)

**Comment by huayunh** [comment]
Only outlined version

**Comment by huayunh** [comment]
One more issue:

![image](https://user-images.githubusercontent.com/8997218/109522002-e535b380-7a7b-11eb-8fa8-8f9252165836.png)

Those disabled button groups should not be elevated, if possible

**Comment by joebochill** [comment]
> Those disabled button groups should not be elevated, if possible

Upon quick look, the elevation/shadow is set on the ButtonGroup, but the disabled gets applied on the inner buttons:
![image](https://user-images.githubusercontent.com/29152776/109523148-06e36a80-7a7d-11eb-8540-4f3c8f59ad59.png)

I don't think I can do a look-back to style a parent based on its children.

**Comment by joebochill** [comment]
![image](https://user-images.githubusercontent.com/29152776/109523367-4ad66f80-7a7d-11eb-9973-b8b6c696a2de.png)
