### ISSUE TITLE
Angular Theme Adjustment

### ISSUE THREAD

**Issue by huayunh** [pxblue/themes#147]
For @emclaug2 , as of the last commit in https://github.com/pxblue/themes/pull/145 

Somehow when I `yarn:angular`, it looks like this. None of the PX Blue icons get properly loaded.
![image](https://user-images.githubusercontent.com/8997218/110984571-53f6f480-8339-11eb-9ebf-1e4b56372b8d.png)

# App Bar & Tab Bar
- [ ] Talk to @joebochill to see what we want for the default/basic color of appbars/toolbars and toolbars. Right now it is set to white200 in light theme, but we may want it to be pure white (white50), as it is a more commonly used color in our project.
# Text Field
- [x] Filled form field, light theme, underline color too dark. 
# Buttons
- [x] Light theme, Raised default/basic colored button should be white — see the design file. The same applies to the basic fab button and the basic mini fab button. What you have for the flat buttons are correct.
- [x] In dark theme, the primary button and the accent buttons' color are still the same. 
- [x] Icon Buttons, light theme, the default button is completely invisible. Should be gray500
- [x] Light theme, "raised default disabled button" and "flat disabled button" have the wrong disabled button style. A raised default disabled button should look the same as a stroked disabled button. See design file.
- [ ] Were you able to make the raised buttons float (have a 4dp shadow) when `:hover`ing on it?
# Select Field
- [x] Light theme disabled underline color wrong
# Sliders
- [x] In light theme, the slider knob should be blue 500
- Not a issue, but just curious what's the difference between a basic slider and a slider "with value"? Their initial values are different?
# Slide Toggle
- [ ] Ask Joe what he did for the basic/default `<Switch />` in React light theme... He had some beef about this during today's review
# Badge
- [x] Dark theme, wrong color for the primary badge
  - [x] There are a lot of similar accidents like this in the dark theme, such as slide toggle, checkboxes, icon buttons, etc. Make sure you've checked all of them.

**Comment by emclaug2** [comment]
> Not a issue, but just curious what's the difference between a basic slider and a slider "with value"? Their initial values are different?
Yep that's the only difference.

**Comment by emclaug2** [comment]
> Were you able to make the raised buttons float (have a 4dp shadow) when :hovering on it?

What about the shadow that happens whenever clicking?  No changes here?

**Comment by emclaug2** [comment]
>  There are a lot of similar accidents like this in the dark theme, such as slide toggle, checkboxes, icon buttons, etc. Make sure you've checked all of them.


BADGE
Default, Primary: Blue[500]
Accent: LB[500]
Warn: Red[500]

RADIO/CHECKBOX/SLIDE TOGGLE
Default, Primary: Blue[200]
Accent: LB[200]
Warn: Red[200]

**Comment by emclaug2** [comment]
> Somehow when I yarn:angular, it looks like this. None of the PX Blue icons get properly loaded.

You need to run `yarn start:angular` and make sure you've checked out the correct branch.  These deployments are what I see locally so icons should all load no problem.

**Comment by huayunh** [comment]
pressed elevation should be the same as the inactive one
