### ISSUE TITLE
NG chips style

### ISSUE THREAD

**Issue by huayunh** [pxblue/themes#156]
## Describe the desired behavior

Make the chips look like https://github.com/pxblue/themes/pull/155

So a disabled primary chip would look the same as a disabled basic chip, which borrows the styles from disabled buttons

## Describe the current behavior

![image](https://user-images.githubusercontent.com/8997218/111513083-cf381c00-8726-11eb-886a-cb3459857b53.png)
![image](https://user-images.githubusercontent.com/8997218/111513104-d4956680-8726-11eb-8b29-da396ce65cae.png)

**Comment by joebochill** [comment]
Not sure if this is something we can do easily in Angular, but we can at least take some time to look into it.

**Comment by joebochill** [comment]
Make sure that we are also disabling pointer events so that we don't get hover behaviors, etc. on disabled chips.

**Comment by joebochill** [comment]
PXBLUE-2067
