### ISSUE TITLE
Angular Drawer Header Dark Mode wrong color

### ISSUE THREAD

**Issue by emclaug2** [pxblue/themes#184]
#### Describe the bug
The Angular Drawer header in dark mode is gray, it should be blue.

#### What is the expected behavior?
Dark mode drawer header should be blue[500] background.

#### What are the steps to reproduce?
Go to the storybook demo app, toggle dark mode.
https://pxblue-components.github.io/angular/?path=/story/components-drawer--with-basic-usage

#### Environment

Chrome, Windows

**Comment by joebochill** [comment]
This happened when we refactored the default colors for dark mode toolbars. We need to add specific rules for the drawer header theme so that it uses blue for the primary toolbar.

**Comment by emclaug2** [comment]
This is fixed now.
