### ISSUE TITLE
Angular and React themes do not exactly match

### ISSUE THREAD

**Issue by emclaug2** [pxblue/themes#31]
#### Describe the bug
Material themes between React and Angular don't match exactly.

#### What is the expected behavior?
The themes demonstrated in the angular and react themes demo match without the use of component-specific css overrides.

#### What are the steps to reproduce?
Open react and angular demo side-by-side.

#### Screenshots or links to minimum reproduction example

I'm listing these issues from most sever to least.

-- Side Nav
1. Uses extensive manual css for overriding default theme colors.

-- Dashboard 
1. Dark theme card backgrounds do not match.

-- Devices (Overview)
1.  Blue theme background colors do not match.
2. Angular demo manually sets mat-table background-color color to be unset.

-- Alarms
1. Angular demo manually sets mat-expansion-panel background-color to be unset.
2. Center panel blue theme background colors do not match.

#### What is your environment?

 Framework
- [X] Angular
- [X] React
- [ ] Ionic
- [ ] React Native

 Browser
- [ ] Internet Explorer
- [ ] Edge
- [ ] Safari
- [X] Chrome
- [ ] Firefox

 Operating System
- [X] MacOS
- [ ] Windows
- [ ] Other

**Comment by jeffvg** [comment]
re-visit this, this has been updated

**Comment by huayunh** [comment]
Probably gonna be updated in our next release, then we can revisit and do a detailed audit on all the material components

**Comment by joebochill** [comment]
We will close this in favor of doing a more detailed audit / fix story in JIRA.
