### ISSUE TITLE
navigation items should use lighter font 

### ISSUE THREAD

**Issue by huayunh** [pxblue/themes#50]
#### Describe the desired behavior
Should use regular and gray 500 for inactive drawer items

#### Describe the current behavior
It uses semibold and black 500 right now

#### Is this request related to a current issue?
Nope

#### Additional Context
![image](https://user-images.githubusercontent.com/8997218/74864378-7a588500-531d-11ea-8e9f-21d2db30895d.png)
It should look like the "For Designers" item (the active item 'For Developers' looks fine)

**Comment by joebochill** [comment]
This doesn't need to be logged as a separate enhancement...it's included in the enhancement for adding expandable sections.
