### ISSUE TITLE
Use component library for theme demo

### ISSUE THREAD

**Issue by huayunh** [pxblue/themes#70]
#### Describe the desired behavior
We can use component lib to demo our theme.

#### Describe the current behavior
It applies our theme to a bunch of material library components. I've seen a project team forking our theme demo and build on top of it. I wonder how many PXBlue components they are actually using. 

#### Is this request related to a current issue?
NO

**Comment by joebochill** [comment]
Now that we have a shared showcase for angular and react, this would be the perfect place to build out the demo with more stuff. We have a story in JIRA to do an overhaul of the themes demo, so we might be able to close this issue in favor of that one.
