### ISSUE TITLE
Update SB themes to include 14px font for drawer menu items

### ISSUE THREAD

**Issue by jeffvg** [pxblue/themes#71]
#### Describe the desired behavior
Font size in all storybook drawers to be same size as the content/documentation.
#### Describe the current behavior
Font size set at 13px
#### Is this request related to a current issue?
No

**Comment by huayunh** [comment]
The storybook theme API does not allow us to theme the side navigation directly; the font size can change only by altering the css in the `manager-head.html`, which is what we are currently doing for Angular component library and React component library.

I am going to close this issue, as our storybook has been fixed using that manager-head trick. 

![image](https://user-images.githubusercontent.com/8997218/90167040-26c57200-dd69-11ea-9989-a9030fdb8976.png)
